var item = document.createElement("div");
 item.className = "item";
var imbox = document.createElement("div");
 imbox.className = "image-box"
item.appendChild(imbox);
var image = document.createElement("img");
 image.style = "height:120px; width: 120px;"
 image.src = cart[index].image;
imbox.appendChild(image);
var info = document.createElement("div");
 info.className = "about";
item.appendChild(info);
var title = document.createElement("h1");
 title.className = "title";
 title.innerHTML = cart[index].name;
info.appendChild(title);
var subtitle = document.createElement("h3");
 subtitle.className = "subtitle";
info.appendChild(subtitle);
var counter = document.createElement("div");
 counter.className = "counter";
item.appendChild(counter);
var btn1 = document.createElement("div");
 btn1.className = "btn";
 btn1.innerHTML = "+"
counter.appendChild(btn1);
var count = document.createElement("div");
 count.className = "count";
 count.innerHTML = "1";
counter.appendChild(count);
var btn2 = document.createElement("div");
 btn2.className = "btn";
 btn2.innerHTML = "-";
counter.appendChild(btn2);
var prices = document.createElement("div");
 prices.className = "prices";
item.appendChild(prices);
var amount = document.createElement("div");
 amount.className = "amount";
 amount.innerHTML = cart[index].price;
prices.appendChild(amount);
var save = document.createElement("div");
 save.className = "save";
 save.innerHTML = "Save";
prices.appendChild(save);
var remove = document.createElement("div");
 remove.className = "remove";
 remove.innerHTML = "remove";
prices.appendChild(remove);
